dev-dependencies = { }

[dependencies]
ovs-fixed = "0.1.1"
base = "0.11.1"
stableheapbtreemap = "1.5.0"
star = "0.1.1"
map = "9.0.1"


[package]
name = "timerTool"
version = "0.0.1"
description = "manage and recover timers in motoko"
repository = "https://github.com/PanIndustrial-Org/timerTool"
keywords = [ "timers" ]
